import os
import shutil
import tempfile
import unittest
from importlib.resources import files
from pathlib import Path

from camelcore.app.logger import logger
from camelcore.app.reports.htmlreport import HtmlReport
from camelcore.app.reports.htmlreportsection import HtmlReportSection
from camelcore.resources import CSS_STYLE


class TestSuite(unittest.TestCase):
    """
    Base class for Camel test suites.
    """

    running_dir = None

    def setUp(self) -> None:
        """
        Sets up the resources before running the test.
        :return: None
        """
        self.running_dir = Path(tempfile.mkdtemp(None, 'camel_'))
        logger.debug(f"Directory for testing: {self.running_dir}")

    def tearDown(self) -> None:
        """
        Removes the working directory after executing the tests.
        :return: None
        """
        if os.environ.get('CAMEL_KEEP_TEST_DIRS') == '1':
            logger.debug(f"Keeping working directory (CAMEL_KEEP_TEST_DIRS): {self.running_dir}")
            return
        if Path(self.running_dir).exists():
            logger.debug(f"Removing working directory: {self.running_dir}")
            shutil.rmtree(self.running_dir)

    @staticmethod
    def get_test_file(path_to_file: Path | str) -> Path:
        """
        Returns the path to the target test file.
        :param path_to_file: Relative path to file starting from the tests folder in resources
        :return: Path to file
        """
        relative_path = Path('resources', 'tests', path_to_file)
        path_out = Path(str(files('camelcore').joinpath(str(relative_path))))
        if not path_out.exists() or not path_out.is_file():
            raise FileNotFoundError(f'Test file not found: {path_out}')
        return path_out

    @staticmethod
    def get_test_dir(path_to_file: Path | str) -> Path:
        """
        Returns the path to the target test file directory.
        :param path_to_file: Relative path to file starting from the tests folder in resources
        :return: Path to file
        """
        relative_path = Path('resources', 'tests', path_to_file)
        path_out = Path(str(files('camelcore').joinpath(str(relative_path))))
        if not path_out.exists() or not path_out.is_dir():
            raise FileNotFoundError(f'Test directory not found: {path_out}')
        return path_out

    @staticmethod
    def export_report_section(report_section: HtmlReportSection, dir_out: Path) -> Path:
        """
        Exports the report section to the output directory.
        This method can be used to inspect the report generated by tools.
        :param dir_out: Output directory
        :param report_section: HTML report section
        :return: Path to the exported report
        """
        path_out = dir_out / 'report_section.html'
        path_out.parent.mkdir(exist_ok=True, parents=True)
        report = HtmlReport(path_out, path_out.parent)
        report.initialize('Exported report section', CSS_STYLE)
        report.add_html_object(report_section)
        report.save()
        logger.info(f'Report section exported to: {path_out}')
        return path_out
